// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3cPa42NXKzfMK11vSB_1NnQft0KPhCWQ',
    appId: '1:624794007159:web:51552c8511ae90578df872',
    messagingSenderId: '624794007159',
    projectId: 'orderin-d6bad',
    authDomain: 'orderin-d6bad.firebaseapp.com',
    storageBucket: 'orderin-d6bad.appspot.com',
    measurementId: 'G-006LTTCL2G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDozWcQeH-V_QAPmZGgwf7VZS5sdx9cGug',
    appId: '1:624794007159:android:43f7226c31f4567f8df872',
    messagingSenderId: '624794007159',
    projectId: 'orderin-d6bad',
    storageBucket: 'orderin-d6bad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLGu2i4EUxKfvIoe90-ytBHd_EagLtjBY',
    appId: '1:624794007159:ios:1cfc4de90a416c1b8df872',
    messagingSenderId: '624794007159',
    projectId: 'orderin-d6bad',
    storageBucket: 'orderin-d6bad.appspot.com',
    iosBundleId: 'com.example.orderinapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLGu2i4EUxKfvIoe90-ytBHd_EagLtjBY',
    appId: '1:624794007159:ios:1cfc4de90a416c1b8df872',
    messagingSenderId: '624794007159',
    projectId: 'orderin-d6bad',
    storageBucket: 'orderin-d6bad.appspot.com',
    iosBundleId: 'com.example.orderinapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3cPa42NXKzfMK11vSB_1NnQft0KPhCWQ',
    appId: '1:624794007159:web:287283393a51987c8df872',
    messagingSenderId: '624794007159',
    projectId: 'orderin-d6bad',
    authDomain: 'orderin-d6bad.firebaseapp.com',
    storageBucket: 'orderin-d6bad.appspot.com',
    measurementId: 'G-HFJ6ZCDW37',
  );
}
